### PR TITLE
Fixes for 0.7+

### PR DESCRIPTION
**Pull request by staticfloat**
Fix depwarns on 0.7

### CODE REVIEW

**Comment by staticfloat** [comment]
@nick-paul this looks good to go now.  Thanks for making such a sweet little package!  :)

**Comment by nick-paul** [comment]
Thanks for updating the package for 0.7+ support!

**Comment by ararslan** [comment]
Could you tag a new release, please?

**Comment by nick-paul** [comment]
Sorry about that, it is up now.

**Comment by ararslan** [comment]
No worries. Thanks!

**Pull request merged**
